In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Users\NMIET\Downloads\archive\Student_performance_data _.csv")
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,2005,15,NaN,2,4,0.135763,17,0,2,0,1,1,1,NaN,4.0
1,1197,16,1.0,-20,4,NaN,0,0,1,1,0,0,1,3.117354,1.0
2,3343,15,0.0,0,999,10.588715,15,0,3,0,0,0,1,-1.500000,2.0
3,2709,Unknown,1.0,1,2,16.208658,-10,0,3,1,0,0,0,3.548521,0.0
4,1436,18,NaN,0,0,200.000000,27,0,1,0,1,0,0,0.248977,4.0
5,1322,15,1.0,-20,1,17.006354,999,0,4,1,0,0,0,2.627694,2.0
6,2473,15,Unknown,0,999,14.372075,23,0,4,1,1,0,0,2.057379,3.0
7,2704,Unknown,0.0,0,1,4.286001,14,1,2,1,1,1,0,2.248338,9.0
8,1901,15,NaN,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0
9,1901,15,NaN,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0
10,3214,17,1.0,2,999,10.982880,10,0,2,0,1,1,0,2.370893,1.0
11,1576,Unknown,0.0,1,2,13.762353,25,0,0,1,0,0,0,0.766405,4.0
12,2164,16,NaN,1,0,15.701437,7,0,3,1,1,0,0,2.952722,2.0
13,3315,17,1.0,-20,1,10.027020,7,0,3,0,0,1,0,2.343331,2.0
14,1612,16,1.0,1,999,18.484369,11,1,3,1,0,0,0,2.771811,2.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          15 non-null     int64
 1   Age                15 non-null     object
 2   Gender             10 non-null     object
 3   Ethnicity          15 non-null     int64
 4   ParentalEducation  15 non-null     int64
 5   StudyTimeWeekly    14 non-null     float64
 6   Absences           15 non-null     int64
 7   Tutoring           15 non-null     object
 8   ParentalSupport    15 non-null     int64
 9   Extracurricular    15 non-null     int64
 10  Sports             15 non-null     int64
 11  Music              15 non-null     int64
 12  Volunteering       15 non-null     int64
 13  GPA                14 non-null     float64
 14  GradeClass         15 non-null     float64
dtypes: float64(3), int64(9), object(3)
memory usage: 1.9+ KB

In [ ]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               5
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      1
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  1
GradeClass           0
dtype: int64

In [ ]:
df.describe()

,StudentID,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000
mean,2191.466667,-3.466667,267.533333,25.424055,78.066667,2.333333,0.533333,0.400000,0.266667,0.200000,1.995917,2.800000
std,730.862296,8.584593,456.574023,50.486587,254.941861,1.112697,0.516398,0.507093,0.457738,0.414039,1.323678,2.077086
min,1197.000000,-20.000000,0.000000,0.135763,-10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.500000,0.000000
25%,1594.000000,0.000000,1.000000,10.687256,8.500000,2.000000,0.000000,0.000000,0.000000,0.000000,2.091711,2.000000
50%,2005.000000,0.000000,2.000000,12.976462,13.000000,2.000000,1.000000,0.000000,0.000000,0.000000,2.295834,2.000000
75%,2706.500000,1.000000,501.500000,16.081853,20.000000,3.000000,1.000000,1.000000,0.500000,0.000000,2.735781,3.500000
max,3343.000000,2.000000,999.000000,200.000000,999.000000,4.000000,1.000000,1.000000,1.000000,1.000000,3.548521,9.000000

In [ ]:
import numpy as np

In [ ]:
df["Gender"] = df["Gender"].replace("Unknown", np.nan)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv(r"C:\Users\NMIET\Downloads\archive\Student_performance_data _.csv")
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,2005,15,NaN,2,4,0.135763,17,0,2,0,1,1,1,NaN,4.0
1,1197,16,1.0,-20,4,NaN,0,0,1,1,0,0,1,3.117354,1.0
2,3343,15,0.0,0,999,10.588715,15,0,3,0,0,0,1,-1.500000,2.0
3,2709,Unknown,1.0,1,2,16.208658,-10,0,3,1,0,0,0,3.548521,0.0
4,1436,18,NaN,0,0,200.000000,27,0,1,0,1,0,0,0.248977,4.0
5,1322,15,1.0,-20,1,17.006354,999,0,4,1,0,0,0,2.627694,2.0
6,2473,15,Unknown,0,999,14.372075,23,0,4,1,1,0,0,2.057379,3.0
7,2704,Unknown,0.0,0,1,4.286001,14,1,2,1,1,1,0,2.248338,9.0
8,1901,15,NaN,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0
9,1901,15,NaN,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0
10,3214,17,1.0,2,999,10.982880,10,0,2,0,1,1,0,2.370893,1.0
11,1576,Unknown,0.0,1,2,13.762353,25,0,0,1,0,0,0,0.766405,4.0
12,2164,16,NaN,1,0,15.701437,7,0,3,1,1,0,0,2.952722,2.0
13,3315,17,1.0,-20,1,10.027020,7,0,3,0,0,1,0,2.343331,2.0
14,1612,16,1.0,1,999,18.484369,11,1,3,1,0,0,0,2.771811,2.0

In [ ]:
df["Gender"] = df["Gender"].replace("Unknown", None)

In [ ]:
df["Age"].value_counts(dropna=False)

15         6
16         3
Unknown    3
17         2
18         1
Name: Age, dtype: int64

In [ ]:
df["Age"] = df["Age"].replace("Unknown", np.nan)

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [ ]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

In [ ]:
df["Age"] = df["Age"].astype(int)

In [ ]:
df["Age"].dtype
df["Age"].isnull().sum()
df["Age"].unique()

array([15, 16, 18, 17])

In [ ]:
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,2005,15,NaN,2,4,0.135763,17,0,2,0,1,1,1,NaN,4.0
1,1197,16,1.0,-20,4,NaN,0,0,1,1,0,0,1,3.117354,1.0
2,3343,15,0.0,0,999,10.588715,15,0,3,0,0,0,1,-1.500000,2.0
3,2709,15,1.0,1,2,16.208658,-10,0,3,1,0,0,0,3.548521,0.0
4,1436,18,NaN,0,0,200.000000,27,0,1,0,1,0,0,0.248977,4.0
5,1322,15,1.0,-20,1,17.006354,999,0,4,1,0,0,0,2.627694,2.0
6,2473,15,Unknown,0,999,14.372075,23,0,4,1,1,0,0,2.057379,3.0
7,2704,15,0.0,0,1,4.286001,14,1,2,1,1,1,0,2.248338,9.0
8,1901,15,NaN,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0
9,1901,15,NaN,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0
10,3214,17,1.0,2,999,10.982880,10,0,2,0,1,1,0,2.370893,1.0
11,1576,15,0.0,1,2,13.762353,25,0,0,1,0,0,0,0.766405,4.0
12,2164,16,NaN,1,0,15.701437,7,0,3,1,1,0,0,2.952722,2.0
13,3315,17,1.0,-20,1,10.027020,7,0,3,0,0,1,0,2.343331,2.0
14,1612,16,1.0,1,999,18.484369,11,1,3,1,0,0,0,2.771811,2.0

In [ ]:
df["Gender"].value_counts(dropna=False)

1.0        6
NaN        5
0.0        3
Unknown    1
Name: Gender, dtype: int64

In [ ]:
df["Gender"] = df["Gender"].replace("Unknown", np.nan)

In [ ]:
df["Gender"] = pd.to_numeric(df["Gender"], errors="coerce")

In [ ]:
df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

In [ ]:
df["Gender"].fillna(1, inplace=True)

In [ ]:
df["Gender"] = df["Gender"].astype(int)

In [ ]:
df["Gender"].value_counts()
df["Gender"].isnull().sum()
df["Gender"].dtype

dtype('int32')

In [ ]:
df["Gender_Label"] = df["Gender"].map({0: "Female", 1: "Male"})

In [ ]:
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,Gender_Label
0,2005,15,1,2,4,0.135763,17,0,2,0,1,1,1,NaN,4.0,Male
1,1197,16,1,-20,4,NaN,0,0,1,1,0,0,1,3.117354,1.0,Male
2,3343,15,0,0,999,10.588715,15,0,3,0,0,0,1,-1.500000,2.0,Female
3,2709,15,1,1,2,16.208658,-10,0,3,1,0,0,0,3.548521,0.0,Male
4,1436,18,1,0,0,200.000000,27,0,1,0,1,0,0,0.248977,4.0,Male
5,1322,15,1,-20,1,17.006354,999,0,4,1,0,0,0,2.627694,2.0,Male
6,2473,15,1,0,999,14.372075,23,0,4,1,1,0,0,2.057379,3.0,Male
7,2704,15,0,0,1,4.286001,14,1,2,1,1,1,0,2.248338,9.0,Female
8,1901,15,1,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0,Male
9,1901,15,1,0,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0,Male
10,3214,17,1,2,999,10.982880,10,0,2,0,1,1,0,2.370893,1.0,Male
11,1576,15,0,1,2,13.762353,25,0,0,1,0,0,0,0.766405,4.0,Female
12,2164,16,1,1,0,15.701437,7,0,3,1,1,0,0,2.952722,2.0,Male
13,3315,17,1,-20,1,10.027020,7,0,3,0,0,1,0,2.343331,2.0,Male
14,1612,16,1,1,999,18.484369,11,1,3,1,0,0,0,2.771811,2.0,Male

In [ ]:
df.drop("Ethnicity", axis=1, inplace=True)

In [ ]:
df

,StudentID,Age,Gender,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,Gender_Label
0,2005,15,1,4,0.135763,17,0,2,0,1,1,1,NaN,4.0,Male
1,1197,16,1,4,NaN,0,0,1,1,0,0,1,3.117354,1.0,Male
2,3343,15,0,999,10.588715,15,0,3,0,0,0,1,-1.500000,2.0,Female
3,2709,15,1,2,16.208658,-10,0,3,1,0,0,0,3.548521,0.0,Male
4,1436,18,1,0,200.000000,27,0,1,0,1,0,0,0.248977,4.0,Male
5,1322,15,1,1,17.006354,999,0,4,1,0,0,0,2.627694,2.0,Male
6,2473,15,1,999,14.372075,23,0,4,1,1,0,0,2.057379,3.0,Male
7,2704,15,0,1,4.286001,14,1,2,1,1,1,0,2.248338,9.0,Female
8,1901,15,1,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0,Male
9,1901,15,1,1,12.190570,13,Yes,2,0,0,0,0,2.194707,3.0,Male
10,3214,17,1,999,10.982880,10,0,2,0,1,1,0,2.370893,1.0,Male
11,1576,15,0,2,13.762353,25,0,0,1,0,0,0,0.766405,4.0,Female
12,2164,16,1,0,15.701437,7,0,3,1,1,0,0,2.952722,2.0,Male
13,3315,17,1,1,10.027020,7,0,3,0,0,1,0,2.343331,2.0,Male
14,1612,16,1,999,18.484369,11,1,3,1,0,0,0,2.771811,2.0,Male

In [ ]:
df.drop(["GPA"], axis=1, inplace=True)

In [ ]:
df

,StudentID,Age,Gender,ParentalEducation,StudyTimeWeekly,Absences,GradeClass,Gender_Label
0,2005,15,1,4,0.135763,17,4.0,Male
1,1197,16,1,4,NaN,0,1.0,Male
2,3343,15,0,999,10.588715,15,2.0,Female
3,2709,15,1,2,16.208658,-10,0.0,Male
4,1436,18,1,0,200.000000,27,4.0,Male
5,1322,15,1,1,17.006354,999,2.0,Male
6,2473,15,1,999,14.372075,23,3.0,Male
7,2704,15,0,1,4.286001,14,9.0,Female
8,1901,15,1,1,12.190570,13,3.0,Male
9,1901,15,1,1,12.190570,13,3.0,Male
10,3214,17,1,999,10.982880,10,1.0,Male
11,1576,15,0,2,13.762353,25,4.0,Female
12,2164,16,1,0,15.701437,7,2.0,Male
13,3315,17,1,1,10.027020,7,2.0,Male
14,1612,16,1,999,18.484369,11,2.0,Male

In [ ]:
df["ParentalEducation"] = df["ParentalEducation"].replace(999, df["ParentalEducation"].mode()[0])

In [ ]:
df["ParentalEducation"].value_counts()

1    9
4    2
2    2
0    2
Name: ParentalEducation, dtype: int64

In [ ]:
df

,StudentID,Age,Gender,ParentalEducation,StudyTimeWeekly,Absences,GradeClass,Gender_Label
0,2005,15,1,4,0.135763,17,4.0,Male
1,1197,16,1,4,NaN,0,1.0,Male
2,3343,15,0,1,10.588715,15,2.0,Female
3,2709,15,1,2,16.208658,-10,0.0,Male
4,1436,18,1,0,200.000000,27,4.0,Male
5,1322,15,1,1,17.006354,999,2.0,Male
6,2473,15,1,1,14.372075,23,3.0,Male
7,2704,15,0,1,4.286001,14,9.0,Female
8,1901,15,1,1,12.190570,13,3.0,Male
9,1901,15,1,1,12.190570,13,3.0,Male
10,3214,17,1,1,10.982880,10,1.0,Male
11,1576,15,0,2,13.762353,25,4.0,Female
12,2164,16,1,0,15.701437,7,2.0,Male
13,3315,17,1,1,10.027020,7,2.0,Male
14,1612,16,1,1,18.484369,11,2.0,Male

In [ ]:
df["StudyTimeWeekly"] = df["StudyTimeWeekly"].clip(lower=0, upper=40)
df["StudyTimeWeekly"].fillna(df["StudyTimeWeekly"].median(), inplace=True)

In [ ]:
df["StudyTimeWeekly"].describe()

count    15.000000
mean     13.927549
std       8.634383
min       0.135763
25%      10.785798
50%      12.976462
75%      15.955048
max      40.000000
Name: StudyTimeWeekly, dtype: float64

In [ ]:
df

,StudentID,Age,Gender,ParentalEducation,StudyTimeWeekly,Absences,GradeClass,Gender_Label
0,2005,15,1,4,0.135763,17,4.0,Male
1,1197,16,1,4,12.976462,0,1.0,Male
2,3343,15,0,1,10.588715,15,2.0,Female
3,2709,15,1,2,16.208658,-10,0.0,Male
4,1436,18,1,0,40.000000,27,4.0,Male
5,1322,15,1,1,17.006354,999,2.0,Male
6,2473,15,1,1,14.372075,23,3.0,Male
7,2704,15,0,1,4.286001,14,9.0,Female
8,1901,15,1,1,12.190570,13,3.0,Male
9,1901,15,1,1,12.190570,13,3.0,Male
10,3214,17,1,1,10.982880,10,1.0,Male
11,1576,15,0,2,13.762353,25,4.0,Female
12,2164,16,1,0,15.701437,7,2.0,Male
13,3315,17,1,1,10.027020,7,2.0,Male
14,1612,16,1,1,18.484369,11,2.0,Male